spring:
  application:
    name: Notification Service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://localhost:8081}
    consumer:
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

logging:
  structured:
    format:
      console: ecs
